spring:
  application:
    name: account-manager

variables:
  logstash: http://localhost:8080
  indiceAccounts: white-board-accounts
server:
  port: 9090
logging:
  path: application/src/main/resources/logback.xml
javaagent:
  patch: D:\WorkSpace\whiteboard\agent\elastic-apm-agent.jar

